### ISSUE TITLE
Didn't working on my server

### ISSUE THREAD

**Issue by yogieputra8** [merencia/node-cron#13]
Hi,

So I tried in my local machine everythings works fine.
Then I try to run my code in the server, it didn't works. It should print **running a task at 13 AM** everyday at 13 AM but my code do nothing at 13 AM. Am I missing something?

my code:
```
var http = require('http');
var port = process.env.PORT || 9090;

var cron = require('node-cron');

cron.schedule('* 00 13 * *', function(){
  console.log('running a task at 13 AM');
});


var server = http.createServer(function (request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.end("Hello World\n");

}).listen(port);

console.log("Node server listening on port " + port);
```

**Comment by merencia** [comment]
Hello @yogieputra8 
First problem is the hour 13:00 AM doesn't exists. With this code your task is going to run at 1:00 PM.

Another problem is `'* 00 13 * *'` specifies a taks that will run every day 13 at 00:00...

So, if you wanna run a task every day at 1:00 AM you must change your cron statement to '0 1 * * *'

**Comment by yogieputra8** [comment]
@merencia 
Aha! I'm sorry, I guess I misstype there :smile: 
By the way I just figured out why my code doesn't work on the server.
It's just because the timezone is different with my local machine.
So I changed it and it's work now.
Thanks for the help :+1:

**Comment by mepatil** [comment]
Hi,
Is this sync or async?
