### ISSUE TITLE
Get next execution time

### ISSUE THREAD

**Issue by larsbo** [merencia/node-cron#14]
I wonder if it's possible to add a method that returns the time of the next scheduled run (after the schedule has been started of course).
This could be a nice improvment for apps with a gui to check the current cron state.

**Comment by merencia** [comment]
Hello @larsbo I think this is a good improvement, I've just add it to milestone v1.2.0.

**Comment by merencia** [comment]
It will be easier to do this by making the issue #15 first.

**Comment by larsbo** [comment]
thank you for the positive reaction. I just want to say that I solved this by using an additional dependency: https://www.npmjs.com/package/cron-parser
 I'm not sure if there is still need for adding that feature to this library :-)

**Comment by merencia** [comment]
Ok, I will close this issue for now

**Comment by KevinNovak** [comment]
Any update on this? Is it possible to get the next execution time?

**Comment by ddelvalledeveloper** [comment]
Plus one here
