### ISSUE TITLE
Cronjobs automatically stop after a certain amount of time

### ISSUE THREAD

**Issue by Cyberuben** [merencia/node-cron#17]
I'm using your module and I noticed that after a certain amount of time (has no fixed amount), the module stops working. 

![log](http://scrnsht.me/u/aIb/raw)

The cronjob runs, executes, this process repeats a few times and then out of nowhere, it just seems to stop working. I'm not sure if this has anything to do with a Node issue (like `setInterval` being bugged) or that it has to do with your module, but I find it strange that this keeps happening.

I can't seem to find out how to debug this, so hopefully anyone else can give me some insight into why this happens and how I can solve it.

I'm using Node version `5.10.1`.

**Comment by merencia** [comment]
Hello @Cyberuben, I'm trying to figure out what's happening so I'd like to know how is your cron expression and how long your job takes to run?

**Comment by Cyberuben** [comment]
```
cron.schedule("0 */2 * * * *", function () {
	// Code to make two APIs convert to eachother's data format
}, true);
```

The cronjob takes +- 40 seconds to run as you can see in my screenshot (`Syncing all %d cards` is where it starts, the other line is where it ends) and I'd like it to run each 2 minutes. It constantly stops after the 12th minute.

**Comment by Cyberuben** [comment]
I'm just going to assume that I made a really stupid mistake because it does work now. I'm sorry for wasting your time!

**Comment by merencia** [comment]
No problem!
