### ISSUE TITLE
"Every 6 hours" task firing every second?

### ISSUE THREAD

**Issue by Artelis** [merencia/node-cron#21]
I've been using node-cron for the last week with - so I thought - no issues. I'm using it to access an API and update a database table every 6 hours, i.e.:

```
var cron = require('node-cron');
cron.schedule('* * */6 * * *', rates.update);
```

On my development PC, I never saw an issue - tested it on my server (hosted on DigitalOcean) and all was well, so I left it running. But then I discovered that I'd been querying the API roughly 14,000 times each day... it turns out the scheduled task was randomly deciding to start firing about once a **second**, not once every 6 hours. And I can't for the life of me figure out why that would be, or how to force it to happen so I can pin it down!

"rates.update" is this:
```
var oxr = require('open-exchange-rates'), fx = require('money');

function updateRates()
{
  //console.log("updateRates()");
  lastUpdate.time = Date.now();

  try
  {
    oxr.set({ app_id: process.env.API_KEY });

    oxr.latest(function(error)
    {
      if(error)
      {
        lastUpdate.status = "ERROR: " + error.toString();
        return;
      }

      fx.rates = oxr.rates;
      fx.base = oxr.base;

      var countries = Object.keys(oxr.rates);
      var rates = countries.map(function(country) { return "('" + country + "', " + oxr.rates[country] + ')'; });
      db.query('REPLACE INTO rates (currencycode, currencyrate) VALUES ' + rates.join(','), function(error)
      {
        if(error)
        {
          lastUpdate.status = "ERROR: Failed to update rates table";
          return;
        }
      });
    });
  }
  catch(e)
  {
    lastUpdate.status = "ERROR: Exception caught while trying to update rates table";
    return;
  }
  
  lastUpdate.status = "SUCCESS";
}
```
"db" is a connection to a MySQL database.

I've tried creating test code that throws exceptions in the scheduled function, I've tried artificially adding delays into it in an attempt to simulate a time-consuming database update, but nothing has revealed a problem. Any suggestions would be gratefully received!

**Comment by Artelis** [comment]
Gah! Never mind, I'm an idiot... `"* * */6 * * *"` doesn't mean "every 6 hours"... it means "every second of every minute of every 6th hour".

Which gives: 14,400 times a day, so that explains that!

**Comment by matt212** [comment]
@Artelis  ,I wanted to run everyday at 9:45 am what would be ?
