### ISSUE TITLE
Able to select timezone

### ISSUE THREAD

**Issue by gabisrm** [merencia/node-cron#22]
I'm actually working in a project which involves scheduling distributed devices to turn them ON or OFF (example: turn off every midnight). The thing is that the time depends on user's timezone, and the server is set to UTC time, so I can't hardcode the scheduling to be '0 0 \* \* *', because this refers to 12 AM in UTC. 

It would be nice to add another argument in the schedule method to specify the timezone, and manages all the UTC offset issues, including the daylight saving time changes.

There's this other node-cron library which implements it, but I had loads of issues with it, so that's why I migrated to this library. The only thing that I miss is this feature.

**Comment by kterusaki** [comment]
Timezone support would be super helpful! I'm working on scheduling email digests, but I want them to be sent out a specific time (e.g. 8am), but considers a user's timezone.

**Comment by hg0605** [comment]
what can we do in our code to handle this timezone issue?

**Comment by merencia** [comment]
I've not decided anything about it yet and my point about it is:
- My premisse in node-cron is "do not use huge dependencies to do a simple thing"; 

So, we can look for a tiny javascript lib to handle timezones or build something (a script in ruby for example) that generates a timezones.json that contains all timezones and offsets, than we can use the offset to convert a Date;

**Comment by merencia** [comment]
@hg0605 you can make a pull request adding this feature to node-cron 😄

**Comment by patthehuman** [comment]
Did this feature ever get implemented

**Comment by merencia** [comment]
not yet

**Comment by ninox92** [comment]
pull request is open #70

**Comment by merencia** [comment]
It will be released on version 2.0
