### ISSUE TITLE
`immediateStart` doesn't actually start the cron job.

### ISSUE THREAD

**Issue by kadishmal** [merencia/node-cron#27]
When `immediateStart !== false`, the module will execute `task.update(new Date())` [source](https://github.com/merencia/node-cron/blob/master/src/scheduled-task.js#L13). But the [`update`](https://github.com/merencia/node-cron/blob/master/src/task.js#L34) function first checks if the time has come to execute the task. However, the time hasn't come because cron job is schedule to be run, say, at midnight.

The `immediateStart` functionality should actually execute the task immediately, not check immediately if the time has come. The current functionality just starts the timer of the cron job. I think this should be documented properly or be changed.

**Comment by merencia** [comment]
Hello @kadishmal when you execute:

```js
cron.schedule('* * * * *', function(){ });
````

A instance of `ScheduledTask` is returned and by default its running (matching the time with cron expression),  if you pass false to `immediateStart` the `ScheduledTask` wont do matching with the cron expression.

In the current model, a `Task` encapsulates the "business rule" and a `ScheduledTask` is a scheduling.

**Comment by kadishmal** [comment]
It should probably be renamed as `immediatelyCheck` and documented accordingly.

**Comment by nathanhornby** [comment]
I agree with @kadishmal - I was also confused why my job wasn't running immediately when started, as the method suggests it will.

**Comment by billmalarky** [comment]
immediateStart defaults to true. The only reason you would use this param would be to set up the cron job with it not running, then at some point in the future start the actual job. This could be accomplished by just creating the actual job at the future time anyways so I'm not entirely sure what the use case of this param is.

Example use case:

```
var scheduledCronJob = cron.schedule('* * * * *', function() {
  console.log('cron job ran');
}, false);

// At this point the cron job isn't running...

// Some time has passed...

scheduledCronJob.start(); // Now the cron job is running every minute.
```

The type of functionality you guys are looking for would be a param with a name like "executeJobOnceOnStart" or something like that. That functionality doesn't exist but you can just do it yourself by calling the job function once directly.

Example:

```
var job = function() {
  console.log('job ran!');
};
job(); // Call it once manually.
cron.schedule('* * * * *', job); // Then schedule the job.
```
