### ISSUE TITLE
Range for hour throws error

### ISSUE THREAD

**Issue by maxfi** [merencia/node-cron#28]
Is setting a range not possible for the hour component of the expression? When I set a `0 8-20 * * 1-5` I get `8-20 is a invalid expression for hour` as an error.

**Comment by merencia** [comment]
Hello @maxfi thanks for your report :)

I've fixed this on pull request #29 and I'm going to release it as soon as possible.

**Comment by merencia** [comment]
@maxfi bug fixed on version 1.1.2.

**Comment by maxfi** [comment]
Thanks @merencia. I'll let you know if there are any issues when I upgrade.
