### ISSUE TITLE
Any function available to know the status of a cron job running?

### ISSUE THREAD

**Issue by jagadeeshpalaniappan** [merencia/node-cron#31]
Just like `task.stop();` 
Does it have any function to know the status of the job whether 'started' or 'stopped' or 'running' ?
`task.getStatus()`

**Comment by merencia** [comment]
Not yet.

@jagadeeshthegeek I have a doubt abut the status, is `started` a `ScheduledTask` waiting to execute and `running` a `ScheduledTask` being executed?

**Comment by jagadeeshthegeek** [comment]
@merencia  Yeah!! Similar to that, so that i can verify my job status in real-time.
Thanks for the response.

**Comment by bhaveshvyas007** [comment]
Any updates on this?
Is this repo even active?

**Comment by bhaveshvyas007** [comment]
It will be my pleasure to contribute.

**Comment by merencia** [comment]
done at #103

**Comment by DeadcatDev** [comment]
@merencia can You give us some examples of checking this? I saw that You added promises, so this kind  of docs will be very helpfull :)
