### ISSUE TITLE
How to stop executing the cron job on condition basis

### ISSUE THREAD

**Issue by SonalGuptaGemini** [merencia/node-cron#33]
I have a program which kicks in at 5pm everyday and runs for every 1min.. Now i want to make the task execution inside this scheduler to be condition based as follows-

var cron = require('node-cron'); 
var bool=false;
cron.schedule('*/1 17-17 \* \* *', function(){
   console.log('running a task every minute for 15th hour');
if(bool)
   {
   console.log("bool is false now");
    this.stop(); //-->Not sure of this 
   }
   else{
    console.log(new Date());
    bool=true;
   }
 });

How can stop this task getting executed after 'bool' becomes false? I do not want to disable this job , as i want this to run every day at the same time but it should stop once the condition becomes false.. Please help..

**Comment by merencia** [comment]
If you stops te job, it wont execute anymore.
But you can do something like this:

```js
var cron = require('node-cron'); 

cron.schedule('*/1 17-17 * * *', function(){
  function shouldExecute(){
    // TODO: implements your condition to skip the current execution and returns false;
    return true; 
  }

  if (shouldExecute()){
    console.log('running a task every minute for 15th hour');
  }
});
```

**Comment by IyiolaOwabumowa** [comment]
Is this answer still scalable in 2021?

**Comment by qasim5611** [comment]
How to stop it From Inside inside the function if specific conditions meet??
