### ISSUE TITLE
Runing cron every day of week ( monday to friday) at 9:00 am (GMT)

### ISSUE THREAD

**Issue by amenzoweb** [merencia/node-cron#34]
Hello could you help please , i didnt understand how to write cron job , i need to run a task every day of work week ( monday to friday) at 9:00 am (morning ) GMT (London Time Zone) 

Thank you very much in advance

( I am sorry i forgot to add this as question because its not an issue)

**Comment by merencia** [comment]
@amenzoweb  you must use [cron syntax](https://github.com/merencia/node-cron#cron-syntax).

In your case e can do something like this:
```js
var cron = require('node-cron');

cron.schedule('0 9 * * Monday-Friday', function(){
  //TODO
}); 
```

About the timezone, node-cron will use the current system timezone.

**Comment by amenzoweb** [comment]
Thank you so much it works like a charm.

Thank you for this module 👍

**Comment by talk2mat2** [comment]
Hi
