### ISSUE TITLE
Start cron immediately and then repeat after certain interval

### ISSUE THREAD

**Issue by bhavika18** [merencia/node-cron#41]
I have a use case where i need to start the cron on application start and thereafter run it after every 30 mins. I could not achieve this using node cron.

**Comment by sebastialonso** [comment]
Is this a problem of not knowing how to write the schedule in cron speak?

This is the one you seem to want `*/30 * * * *` (seconds are not used here)

For more complex schedules, I'd recommend [Crontab guru](https://crontab.guru/)

**Comment by besserwisser** [comment]
I think he wants the task to be executed on application start and then every 30 minutes. What you suggesting is not the same. With your suggestion the first execution will be in 30 minutes and not immediately. I am dealing with the same problem and would be glad for a clean solution

**Comment by besserwisser** [comment]
I think he wants the task to be executed on application start and then every 30 minutes. What you suggesting is not the same. With your suggestion the first execution will be in 30 minutes and not immediately. I solved this issue by defining the callback function outside the cron.job context. Then you can immediately call it afterwards and still pass it as a parameter to the cron.job function

For example:
```
var cron = require('cron');
function EngCB(){
     //Code you want to execute periodically! 
   }
EngCB(); //immediate execution

var cronJob = cron.job("*/1 * * * *", EngCB, false) //periodically execution. First after 1 minute. 
cronJob.start();
```
