### ISSUE TITLE
How to increase the execution time ? 

### ISSUE THREAD

**Issue by abdulbasit170** [merencia/node-cron#43]
I have a script to run having hundreds of rest API calls for reporting purposes. can anyone please tell how to increase the execution time for this ? i believe there is limit to the execution time in node by default

**Comment by phihag** [comment]
What makes you believe that there is a limit to the execution time on node.js? Do you get an error; if so, which one?

**Comment by abdulbasit170** [comment]
I have script to run containing multiple API calls to retrieve and update data. 
I was running that client side script from browser. i needed to run that automatically like a day end job. 
I transferred that script to NODE JS. as NODE enables us to run JS on server side. 
now i am running the job as cron job in node js. but it stops running after 2 minutes. as i am maintaining the log. 
can you please tell that how to increase the script time to run so that it runs as long as all process gets done. 

Sorry for the long message

**Comment by phihag** [comment]
This is a technical forum; messages should be long on technical details.

There is no script time limit, most definitely not 20 minutes (on some systems, there may be a limit on the order of 68 years, but that would be a limit of the operating system and not node.js or node-cron). I am regularly running jobs upwards of 20 minutes.

Please do post the [technical details I asked about](https://github.com/merencia/node-cron/issues/43#issuecomment-282465561), namely the stack trace (if any) and technical information (e.g. syscall log, example code that triggers the behavior, platform information, how you detect that your program stops running etc.).

It is very likely that there is a simple bug in your program. This is not the place to discuss bugs in your program. The correct place for that is [StackOverflow](https://stackoverflow.com/) and other similar programming forums. Make sure to provide a [self-contained example](http://sscce.org/).

**Comment by abdulbasit170** [comment]
Thanks for the detailed reply

I fetch data from a third party website through API. then i perform some calculations. then I update lists on SharePoint in Loop like follows 

for (var k = 0; k < liveItems.length; k++) {
	updateListItem(listName, liveItems[k].ID, itemProperties, function (err, result) {
		console.log('Item updated');
	});
}

like above i update around 5000 records daily. but when my cron job runs. only few records arround 200 gets updated. as i am writing on the consoles on every update call back. i get to know that a time out must happen  that only few records have been updated. 

If there is really no time out on node. i should look into my code where the bug is. 

but as far as it seemed, there is limitation for script to run. as if run update arround 100 records only. they gets updated perfectly. 

P.S - I am new to Node.

**Comment by phihag** [comment]
As a start, make sure to check all errors: If `err` is something true-ish in that code sample, you should at least log the error, like this:

```
for (const li of liveItems) {
	updateListItem(listName, li.ID, itemProperties, function (err, result) {
		if (err) {
			console.error('updateListItem failed on ' + li.ID, err);
			return;
		}
		console.log('Item updated');
	});
}
```

Also note that even if there was a timeout, this code is unlikely to hit it: `updateListItem` seems to be an asynchronous function (it has a callback instead of a return value). Although there are exceptions, asynchronous functions typically send a request very quickly, then wait for the remote host, and then parse the response. The error handling code will tell you more details.

The problem may be that you're submitting 5000 requests at once and overwhelming the remote server (depending on request size, I'd call the remote an attack target instead of a server you're using). You may want to use `async.mapLimit` or similar to limit the number of simultaneous requests.

**Comment by abdulbasit170** [comment]
Yes, got it. err logging should be the thing i am missing. let me check.

Thanks a lot for the help. :)

**Comment by merencia** [comment]
Hello,

@phihag thanks for your support!

@abdulbasit170 I will close the issue for now, because I think it isn't related to the node-cron library.
