### ISSUE TITLE
Run a task every day at 8am

### ISSUE THREAD

**Issue by junerockwell** [merencia/node-cron#44]
Would I only need to do the following to run a task every day (including weekdays) at 8am:
`````
cron.schedule('0 8 * * *', function() {
  // run task
});
`````
Correct? Or would I do:
`````
cron.schedule('0 8 * * 0-7', function() {
});
`````
`0-7` for Monday to Sunday.

I got an error saying that "Monday to Sunday" isn't valid. So I used `0-7` instead.

![screen shot 2017-03-08 at 3 15 29 pm](https://cloud.githubusercontent.com/assets/5051574/23728889/f6e89e9a-0413-11e7-95b6-143ddf80f159.png)

**Comment by merencia** [comment]
Hello @junerockwell 

The first option will work for you. When you use`*` you're telling to the scheduler: run on every available option.

About the error. I've testes and there is a bug on week day scheduling. If you need to restrict by day of week like run from monday to friday you could use '1-5', in this case 0 is monday and 5 is friday.
