### ISSUE TITLE
Unique ID for cron

### ISSUE THREAD

**Issue by jnordling** [merencia/node-cron#49]
Thanks for the great module.

I have an application that dynamically creates crons based on user account input. I have had no problem creating the jobs dynamically. I just don't see a way to get/store a unique reference to the cron so later I can retrieve and stop/remove the cron is user wants to stop it. The only other module I have found that seems to do this is https://github.com/NineCollective/node-crontab but it seem much less supported and has some issues with have the same ID for multiple crons.

Are there currently any ways to do this with this module?

Thanks!

**Comment by merencia** [comment]
Hello @jnordling 

The current version of node-cron doesn't have a unique id for a job, but when you call `cron.schedule` it returns a `ScheduledTask` if you wants to stop a job, you should keep this object in a variable. Take a look on [this example](https://github.com/merencia/node-cron#stop).

Alternatively you can store the jobs in a key value structure and retrieve the `ScheduledTask` posteriorly. Something like this:
```js
const uuidV4 = require('uuid/v4');
const cron = require('node-cron');

var jobStorage = {};
var task = cron.schedule('* * * * *', function() {
  console.log('will not execute anymore, nor be able to restart');
});
var taksId = uuidV4();
jobStorage[taskId] = task;

// ...

jobStorage[taskId].stop();

```

I think it's a no so elegant workaround, but a alternative solution.

**Comment by ahmadsibisnis** [comment]
So, is it solve at current [version](https://github.com/node-cron/node-cron/releases/latest)  ?

**Comment by alan345** [comment]
how can we save the cron Id in the database and maybe stop it later?

**Comment by azakero** [comment]
Has this feature been added? Please acknowledge!
