### ISSUE TITLE
Job doesn't run Linux/Centos Forked Process

### ISSUE THREAD

**Issue by camj256** [merencia/node-cron#55]
I've got a job set to run daily at 9am. (0 0 9 * * *)

I have a fairly large application that spawns multiple processes. This is meant to be a daily summary report. It runs fine on my dev machine (windows) but doesn't run at all on Centos.

I'm going to do some more digging but I'm wondering if this is a known thing or not?

**Comment by adityamertia** [comment]
I face the same issue. The job doesn't run in centos. Fairly long-standing issue. Is there a resolution to this yet?

**Comment by merencia** [comment]
Hello, 

No, there is no resolution for that.

Actually I never tried to use node-cron at Centos. This happens in every task? Your scheduled task is in a spawned process?

**Comment by merencia** [comment]
Actually I've created a [lib](http://sidequestjs.com/) that schedule tasks in spawned process. And is working just fine in a Debian.
