### ISSUE TITLE
Rogue Job

### ISSUE THREAD

**Issue by scottymeyers** [merencia/node-cron#56]
I have a single task scheduled twice daily (8am & 4pm). Now, I'm having an issue w/ the job running twice @ each scheduled time a few seconds apart. I've removed the task completely from my application and now it's running a single time as it should, but there is no reference to it in my application.

If it matters, my app was deployed w/ Dokku and I haven't established any caching mechanism.

**Comment by merencia** [comment]
Hello @scottymeyers 

Do you still have this problem?
