### ISSUE TITLE
don't run cron if already running

### ISSUE THREAD

**Issue by pixelpaulaus** [merencia/node-cron#57]
is there any inbuilt function to only run the next tick if there is no other tick of the cronjob running still? In case i have a cronjob running every few seconds but sometimes it might finish slower then normal.

**Comment by merencia** [comment]
Hello @pixelpaulaus 

I using a [setInterval](https://github.com/merencia/node-cron/blob/81548ebca4048d6b5676e4fddec39ad3335c1ef4/src/scheduled-task.js#L30) to check periodically whether a task needs to be performed, so when run time of your task is greater than the runtime node-cron will [miss executions](https://github.com/merencia/node-cron/issues/38).
