### ISSUE TITLE
No stop task handler for cron jobs

### ISSUE THREAD

**Issue by RecuencoJones** [merencia/node-cron#6]
I would like to be able to stop my cron tasks programmatically aside from killing the whole task itself.

For that purpose, https://github.com/merencia/node-cron/pull/5 has been created.

Regards.

**Comment by merencia** [comment]
Hello @RecuencoJones, thank you for your contribution. 
I've merged your PR, but before release it on npm I had a doubt...

Isn't it better to create a class to manage the scheduled task?

For example, we could create a class like `ScheduledTask` put the `setInterval` and `clearInterval` invocation into this class and instantiate a `ScheduledTask` whit a `Task` and delegate the responsibility to stop and start a task for this class.

I think this way you can also restar a scheduled job, invoking  stop and start methods.

What do you think about it?

**Comment by RecuencoJones** [comment]
To me it looks perfect, I don't like either to have the user handling an intervalObject, plus we could be even able to perform a much better destroy of the task, rather than just cancelling the interval.

**Comment by merencia** [comment]
@RecuencoJones I've opened the pull request #8 adding the `ScheduledTask` class, is it fine to you?

**Comment by merencia** [comment]
refs #9

**Comment by RecuencoJones** [comment]
Solved in #9
