### ISSUE TITLE
it doesnt wait for previous execution to complete

### ISSUE THREAD

**Issue by praveengarg07** [merencia/node-cron#63]
it doesnt wait for previous execution to complete

**Comment by ubskogentix** [comment]
Any alternative solutions for this question?

**Comment by matteocontrini** [comment]
Why should it? Cron jobs usually never have that feature

**Comment by mohsin917** [comment]
@matteocontrini is right that cron jobs usually do not wait for completing the previous task. You have to implement a workaround..

You can add a boolean flag for your execution.

`class YourClass {

    public cronTask: any;

    public executionCompleted: boolean = true;

    constructor() { 

        this.startCron();
    }

    startCron(){
        this.cronTask = cron.schedule('* * * * *', () => {
            if(executionCompleted == true){
                this.yourLengthyTask();
            }
        });
    }


    yourLengthyTask() {
        
        return new Promise((resolve, reject) => {
            this.executionCompleted = false;

            //
            //
            // Your length task goes here.
            //
            //

            this.executionCompleted = true;
            resolve(true);
        })
        
    }
}`

This is if your cron is very short...

Or else you can just start a cronTask and when your method is called just stop cron "this.cronTask.stop();" before execution and when execution is completed, start crow task again. But it is a dirty approach.
