### ISSUE TITLE
How to set timezone.

### ISSUE THREAD

**Issue by dhksrini** [merencia/node-cron#68]
I want to know how to set the timezone for node-cron. My local node server it's working fine, Is it I have to set the timezone for the production server? How to set for different regions. 
Thanks in advance.

**Comment by hsnkh** [comment]
i also have this problem

**Comment by merencia** [comment]
Hi.
node-cron uses the server timezone, so it doesn't support set a timezone.

There is a [issue](https://github.com/merencia/node-cron/issues/22) requesting timezone support, but I'm not programming with node lately.
