### ISSUE TITLE
Schedule functions 1 more time than the last day

### ISSUE THREAD

**Issue by Gobluebro** [merencia/node-cron#76]
Had an issue where I was running a scheduled function that looks like this:

`cron.schedule('30 21 * * Tuesday,Wednesday,Thursday', function(){`
`      console.log('warning ' + new Date());`
`});`

First day it printed:
warning (date format)

Second day it printed:
warning (date format)
warning (date format)

Third day it printed:
warning (date format)
warning (date format)
warning (date format)

at which point I just stopped it.

If being detailed helps, I run the program on amazon's linux machine and use the command screen to start the program so I can close my SSH terminal and keep it running.

**Comment by akprats33** [comment]
You might be scheduling your `cron` multiple number of times in the same process. Please make sure that you schedule that only once.

**Comment by Gobluebro** [comment]
@akprats33 Ah I do have 3 crons scheduled. How would I go about having multiple crons scheduled?

**Comment by merencia** [comment]
@Gobluebro I've create a cron job like this:
```js
cron.schedule('32,33,34 * * * Tuesday,Wednesday,Thursday', function(){
  console.log('warning ' + new Date());
});
```

I got this as result:
```
warning Tue Mar 06 2018 15:32:00 GMT-0300 (-03)
warning Tue Mar 06 2018 15:33:00 GMT-0300 (-03)
warning Tue Mar 06 2018 15:34:00 GMT-0300 (-03)
```

When you create a scheduled job like `'30 21 * * Tuesday,Wednesday,Thursday'` it means that your job will perform every Tuesday, Wednesday or Thursday at 21:30. 

Have you setted it just once?

**Comment by Gobluebro** [comment]
@merencia Oh I never thought of doing something like that.

Though my code looks more like this currently
```javascript
cron.schedule('0 21 * * Tuesday,Wednesday,Thursday', function(){
    console.log('start command' + new Date());
    startfunction();
});
```
```javascript
cron.schedule('30 21 * * Tuesday,Wednesday,Thursday', function(){
    console.log('5 minute warning' + new Date());
});
```
```javascript
cron.schedule('35 21 * * Tuesday,Wednesday,Thursday', function(){
    console.log('end command' + new Date());
    endfunction();
});
```

Should I do something more like this?
```javascript
cron.schedule('0,30,35 * * * Tuesday,Wednesday,Thursday', function(){
   if(Date.getMinutes() == 30)
   {  
      console.log('warning ' + new Date());
   }
});
```

**Comment by merencia** [comment]
> Should I do something more like this?

If you need execute the same task every minute 0, 30 and 35, yes.

About your current code I have a important point:
Node.js is single thread, so if you block your i.o on `startfunction` for 31 min it'll prevent `node-cron` to check and run your next task.

**Comment by Gobluebro** [comment]
Okay thanks for the help! 👍

**Comment by haifahrul** [comment]
example of my code :

```js
var cron = require('node-cron');
var moment = require('moment');

var task =  new cron('0 00 16 28-31 * *, function() {
  if (isLastDayOfMonth()) {
    doSomeStuff()
  }
}, null, true, 'America/Los_Angeles');

function isLastDayOfMonth(){
  const currentDay  =  moment().format('YYYY-MM-DD');
  const lastDayOfCurrentMonth  =  moment(date).endOf('month').format('YYYY-MM-DD');

  if (currentDate === lastDayOfCurrentMonth) {
    return true;
  } else {
    return false;
  }
}

function doSomeStuff(){
  // your task here.
}
```

The cron will be run every 28 - 31 day, and then check whether current day is a last day of current month. And it's work.

I have add in day_of_month function to check it, if user input L, then day_of_month will be set to 28-31
