### ISSUE TITLE
Schedule cron last day of month

### ISSUE THREAD

**Issue by aphavichitr** [merencia/node-cron#77]
Is there a way to schedule cron to run the last day of month without creating multiple cron jobs? For example Jan 31st 6AM, Feb 28/29 6AM, March 30 6AM, etc...

**Comment by merencia** [comment]
Hello @aphavichitr 

This kind of scheduling is not supported.

You may do something like this:

```js
var cron = require('node-cron');

cron.schedule('0 6 28-31 * *', function(){
  if(isLastDayOfMonth()){
    doSomeStuff()
  }
});

function isLastDayOfMonth(){
  //...
}

function doSomeStuff(){
  // your task here.
}
```

**Comment by haifahrul** [comment]
Hey @aphavichitr , did you solved it?

**Comment by aphavichitr** [comment]
> Hey @aphavichitr , did you solved it?

Yes, I did what @merencia mentioned. You have to check each month to see if those days (28-31) are the last day of the month. Also need to check for leap years (29). Not the cleanest way of doing it, but it works.

**Comment by haifahrul** [comment]
@aphavichitr My Code

```JS
var CronJob = require('cron').CronJob;
var moment = require('moment');

new CronJob('0 00 16 28-31 * *, function() {
  console.log('You will see this message every second');

  if (isLastDayOfMonth()) {
    doSomeStuff()
  }
}, null, true, 'America/Los_Angeles');

function isLastDayOfMonth(){
  const currentDay  =  moment().format('YYYY-MM-DD');
  const lastDayOfCurrentMonth  =  moment(date).endOf('month').format('YYYY-MM-DD');

  if (currentDate === lastDayOfCurrentMonth) {
    return true;
  } else {
    return false;
  }
}

function doSomeStuff(){
  // your task here.
}
```

The cron will be run every 28 - 31 day, and then check whether current day is a last day of current month. And it's work.

I have add in day_of_month function to check it, if user input **L**, then day_of_month will be set to 28-31
