### ISSUE TITLE
Cron schedule every sunday runs multiple times each sunday

### ISSUE THREAD

**Issue by MiguelCosme** [merencia/node-cron#81]
Hi,

I'm using the node-cron in a MEAN app to create new documents for mongodb each Sunday. My problem is that the cron task runs every five minutes each Sunday, although I have properly done my post method to not create duplicates it bothers me to have all that computing done for nothing. Is this the normal behavior of the function? 

My code is bellow:

cron.schedule('* * * Sunday', function(){}

P.S. Already tried the task.stop(); but instead of running once and stop until next Sunday, it just doesn't run.

**Comment by merencia** [comment]
> The problem is that I want to know if I just specified the weekday should it run the task more than once on that specific weekday?

If you use `*`for some filed it means every value is valid, so, if you want to perform the job once a day chose a specific time to it and set it on cron expression.

Like this: `0 3 * * Sunday`, thus will perform you task at 03:00 am every sunday.

**Comment by MiguelCosme** [comment]
Thank you for the help!   @merencia
