### ISSUE TITLE
Question about cron pattern

### ISSUE THREAD

**Issue by aurelius0523** [merencia/node-cron#84]
Hi, I wanted to run a task every minute from 9am to 6pm on Monday to Friday using the following cron pattern but the behavior seems rather erratic. The job never seem to continue even at 10am the next day. Am I missing something?

```js
cron.schedule(
  '* */1 9-17 * * 1-5',
  () => {
      //code
  },
  true
);
```

**Comment by merencia** [comment]
Hey @aurelius0523 

May you try this:
```js
cron.schedule(
  '* 9-17 * * 1-5',
  () => {
      //code
  },
  true
);
```

Using your code the cron will run every second, from 9am to 6pm because the first param is optional, if you omit it as I do the default value (zero) will be used. Another thing I'v dropped the `*/1` you may use only * to set "every minute".

**Comment by aurelius0523** [comment]
With the cron pattern I've provided it runs every minute but I'm guessing that there was a part of my code that causes my result to not be apparent. At any rate, with your pattern and some code fix on my mini-app it's not working perfectly. Thanks!
