### ISSUE TITLE
Crone running same task multiple times

### ISSUE THREAD

**Issue by Blackpack2003** [merencia/node-cron#85]
Crone schedule was set to (* 13 * * * ) and keepted running during one hour continuously, I had to shut down my pm2.

**Comment by merencia** [comment]
Hey @Blackpack2003! 

As you've setted `* 13 * * *` the `*` means every value is valid.

So, `* 13 * * *` means: Run the job, every minute, at 13 hour, every day, every month, every day of week.

So if you want to run once you cannot use * for minute. A common value for that is use zero, like:
`0 13 * * *` or a specific minute that you prefer.

**Comment by altras** [comment]
I hope this brings more visibility https://crontab.guru/#*_13_*_*_*
