### ISSUE TITLE
Time expression steps

### ISSUE THREAD

**Issue by bmy4415** [merencia/node-cron#87]
Hello, I am happily using node-cron.
But because I am new to node-cron, I cannot exactly make time expression.
I want to make something start every minute such that (minute % 5 == 1).
For example I want to do something at 1, 6, 11, 16, ... 51, 56 minute.
I did '1-56/5 * * * *' but it didn't work. (Rather, it starts task at (minute % 5 == 0) which is same as */5)

Can you help me?

**Comment by merencia** [comment]
Hey @bmy4415 

Thanks to use node-cron :)

I've understood what you need to do, and I know that it will no work at all. Node-cron implements this spec for cron: https://www.gnu.org/software/mcron/manual/html_node/Crontab-file.html and this feature is not supported.
