### ISSUE TITLE
AWS Linux

### ISSUE THREAD

**Issue by godsmustbcrazy** [merencia/node-cron#88]
The node-cron works on my local ubuntu and my local mac but it does not work on the Amazon Linux ( which is what Beanstalk uses)
Anyone else facing the same issue?

**Comment by godsmustbcrazy** [comment]
For anyone else who ran into this issue. This alternative npm package does work on AWS Linux

https://www.npmjs.com/package/cron

**Comment by merencia** [comment]
Hey  @godsmustbcrazy 

Actually I never tried to run it on at Amazon Linux.
I've used node-cron inside a docker image at EB, so, my env was a debian... 

So, Thanks for your alternative! 
I'm closing the issue for now.
