### ISSUE TITLE
Node mail scheduler sending multiple mail behind multiple server instance hosted on cloud

### ISSUE THREAD

**Issue by shashi97** [merencia/node-cron#93]
I have a Node.js app running in multiple instances on google Cloud. The app has - among others - a scheduler ("node-cron": "^1.3.0") which sends a reminder mail to customers once every day. Now with multiple instances of the app, I get multiple mails - for each instance to same customer every day.

Is there a solution for this?

**Comment by merencia** [comment]
Hello @shashi97!

I think this is not a node-cron problem, but at my work I got the same problem using Java technologies, as you have a many servers I can see 3 alternatives.

1 - Create a app just for batch processing and jobs, that is deployed without replicas.
2 - Use a env variable linke `JOBS_ENABLED=true` to restrict the scheduler in a unique instance.
3 - Use some distributed lock, you may use redis for that: https://redis.io/topics/distlock. IMHO this is the better option.

We're using the option 3 😃

**Comment by shashi97** [comment]
Thanks @merencia !

I think third one is better solution.

**Comment by paulocastellano** [comment]
@merencia maybe add some plugin, or extension for work with Redis it's a great improvement.

Laravel do it, you sync the commands with Redis and you can control how many servers you want to run it.

Works 👌
