### ISSUE TITLE
Execute Every 10 seconds

### ISSUE THREAD

**Issue by bhaveshvyas007** [merencia/node-cron#94]
I tried this '10 * * * *' as well as '10 * * * *' patterns, but it doesn't run the cron job every 10 seconds.
Please guide what is wrong

I need to run the cron job every x seconds

**Comment by merencia** [comment]
Hey @bhaveshvyas007 

To do that, you need to use the following cron pattern:`*/10 * * * * *`

**Comment by bhaveshvyas007** [comment]
Thanks. I also had figured out later
