### ISSUE TITLE
Running a job every 5 seconds

### ISSUE THREAD

**Issue by justinith** [merencia/node-cron#95]
Hi, I can't seem to get a cron job to run in seconds. 

This is what I have:
```
const cron = require("node-cron");
var fiveSec = cron.schedule("5 * * * * *", function() {
    console.log("running a task every 5 seconds");
},false);

fiveSec.start();
```

I have a function that works every minute, but just having syntax struggle with seconds...
Any help is much appreciated!

**Comment by oferze** [comment]
For all the lost souls that arrived here, the reason is that you need to use an interval syntax: `*/5` , such as:

```
cron.schedule('*/5 * * * * *', () => {
  console.log('running a task every 5 sec')
});
```
